---
title: "Cherry_Picker"
author: "Gianluca Pegoraro"
date: "November 15, 2016"
output: html_document
---
## Aim

```{r loadAndClean}
library(plyr)
library(ggplot2)
library(data.table)
library(stringr)
library(knitr)
```

```{r, include=FALSE, warning=FALSE}
opts_chunk$set(fig.path="output/", cache = TRUE, dev=c("png"), message=FALSE, warning=FALSE)
theme_set(theme_minimal())
```

## Import Data

Generate some test data (Full source plate). 
```{r}
set.seed(161115)

n_source <- 20

input <- data.table(source_rack = rep(paste0("HTIF000", 1:n_source), each = 96),
                    source_id =  paste0("ID_", sample(1:10000, 96*n_source)),
                    source_pos = rep(1:96, n_source),
                    source_col = rep(1:12, each = 8),
                    source_row = rep(1:8, 12),
                    source_flag = sample(c("Hit", "Miss"), 96*n_source, replace = TRUE, prob = c(0.35, 0.65)))
```

Randomize empty wells in the Source plates (`Miss`)
```{r}
input[source_flag == "Miss", source_id := NA]
```

Plot the Source plates layout
```{r}
input_plot <- ggplot(input, aes(x = source_col, y = source_row, label = source_id))
input_plot + geom_text(size = 1.5) +
            facet_wrap( ~ source_rack) +
            scale_x_continuous(lim = c(1, 12), breaks = 1:12) +
            scale_y_reverse(lim = c(8, 1), breaks = 1:8, labels = LETTERS[1:8]) +
            ggtitle("Source Plates Layout")
```

Filter out empty wells to generate 
```{r}
output <- input[source_flag == "Hit",]
```

Assign the destination positions. Only the internal 60 wells (Excluding rows A/H and columns 1/12) are used. 
```{r}
output[, `:=`(dest_rack = rep(paste0("HTIF000", (n_source+1):(n_source*4)), each = 60),
                 dest_pos = as.vector(outer((10:15), seq(0, 72, 8), FUN = "+")),
                 dest_col = rep(2:11, each = 6),
                 dest_row = rep(2:7, 10))]
```

Plot the Source plates layout
```{r}
output_plot <- ggplot(output, aes(x = dest_col, y = dest_row, label = source_id))
output_plot + geom_text(size = 1.5) +
            facet_wrap( ~ dest_rack) +
            scale_x_continuous(lim = c(1, 12), breaks = 1:12) +
            scale_y_reverse(lim = c(8, 1), breaks = 1:8, labels = LETTERS[1:8]) +
            ggtitle("Dest Plates Layout")
```

```{r}
write.csv(x = output, 
          file = "output/Cherry_Pick_Worklist.csv", 
          quote = FALSE, 
          col.names = TRUE,
          row.names = FALSE)
```
Document the information about the analysis session
```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```